//Sebuah file untuk mengubah text menjadi arabic
var huruf = [
	'a', 'i', 'u',
	'ba', 'bi', 'bu',
	'ta', 'ti', 'tu',
	'tsa', 'tsi', 'tsu',
	'ja', 'ji', 'ju',
	'ha`', 'hi`', 'hu`',
	'kha`', 'khi`', 'khu`',
	'da', 'di', 'du',
	'dza', 'dzi', 'dzu',
	'ra', 'ri', 'ru',
	'za', 'zi', 'zu',
	'sa', 'si', 'su',
	'sya', 'syi', 'syu',
	'sha', 'shi', 'shu',
	'dha', 'dhi', 'dhu',
	'tha', 'thi', 'thu',
	'dhza', 'dhzi', 'dhzu',
	'a`', 'i`', 'u`',
	'gha', 'ghi', 'ghu',
	'fa', 'fi', 'fu',
	'qa', 'qi', 'qu',
	'ka', 'ki', 'ku',
	'la', 'li', 'lu',
	'ma', 'mi', 'mu',
	'na', 'ni', 'nu',
	'wa', 'wi', 'wu',
	'ha', 'hi', 'hu',
	'ya', 'yi', 'yu',
];